[window]
padding.x = 8
padding.y = 8
opacity = 0.8
decorations = "none"
dynamic_padding = true
startup_mode = "Maximized"
option_as_alt = 'Both'

[font]
size = 30.0

[font.normal]
# family = "Google Sans Code"
# family = "VictorMono Nerd Font"
# family = "Iosevka Nerd Font"
# family = "Hack Nerd Font"
# family = "Ioskeley Mono"
# family = "Fixedsys Excelsior"
# family = "Iosevka Nerd Font"
# family = "Monocraft"
# family = "Miracode"
# style = "Regular"
#
# â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
# ğŸ–Œï¸ Colors (Tokyo Night Storm inspired)
# â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
[colors.primary]
background = "0x000000"
foreground = "0xc0caf5"


[colors.normal]
black = "0x1a1b26"
red = "0xf7768e"
green = "0x9ece6a"
yellow = "0xe0af68"
blue = "0x7aa2f7"
magenta = "0xbb9af7"
cyan = "0x7dcfff"
white = "0xa9b1d6"

[colors.bright]
black = "0x414868"
red = "0xf7768e"
green = "0x9ece6a"
yellow = "0xe0af68"
blue = "0x7aa2f7"
magenta = "0xbb9af7"
cyan = "0x7dcfff"
white = "0xc0caf5"

